[build]
  command = "npm install && npx prisma generate && next build"
  publish = ".next"

[build.environment]
  PRISMA_SKIP_POSTINSTALL_GENERATE = "true"
  NEXT_OTEL_VERBOSE = "1"

[[plugins]]
  package = "@netlify/plugin-nextjs"